// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

/*
Package testpb is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	EchoRequest
	EchoResponse
	AddRequest
	AddResponse
*/
package testpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Str string `protobuf:"bytes,1,opt,name=str" json:"str"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoRequest) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type EchoResponse struct {
	Str string `protobuf:"bytes,1,opt,name=str" json:"str"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoResponse) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type AddRequest struct {
	A int64 `protobuf:"varint,1,opt,name=a" json:"a"`
	B int64 `protobuf:"varint,2,opt,name=b" json:"b"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *AddRequest) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type AddResponse struct {
	Sum int64 `protobuf:"varint,1,opt,name=sum" json:"sum"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "testpb.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "testpb.EchoResponse")
	proto.RegisterType((*AddRequest)(nil), "testpb.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "testpb.AddResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x49, 0x2d, 0x2e, 0x29, 0x48, 0x52, 0x92,
	0xe7, 0xe2, 0x76, 0x4d, 0xce, 0xc8, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0,
	0x62, 0x2e, 0x2e, 0x29, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x14, 0xb8,
	0x78, 0x20, 0x0a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xb1, 0xa8, 0xd0, 0xe0, 0xe2, 0x72, 0x4c,
	0x49, 0x81, 0x99, 0xc0, 0xc3, 0xc5, 0x98, 0x08, 0x96, 0x65, 0x0e, 0x62, 0x4c, 0x04, 0xf1, 0x92,
	0x24, 0x98, 0x20, 0x3c, 0xb0, 0x65, 0x60, 0x95, 0x48, 0x46, 0x95, 0xe6, 0x42, 0x15, 0x83, 0x98,
	0x49, 0x6c, 0x60, 0xc7, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xd6, 0x1a, 0xda, 0xaa,
	0x00, 0x00, 0x00,
}
